//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gherkin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gherkin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string DlgFind_Find {
            get {
                return ResourceManager.GetString("DlgFind_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string DlgFind_FindNext {
            get {
                return ResourceManager.GetString("DlgFind_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string DlgFind_MachCase {
            get {
                return ResourceManager.GetString("DlgFind_MachCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        public static string DlgFind_MachWholdWord {
            get {
                return ResourceManager.GetString("DlgFind_MachWholdWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string DlgFind_RegularExpression {
            get {
                return ResourceManager.GetString("DlgFind_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string DlgFind_Replace {
            get {
                return ResourceManager.GetString("DlgFind_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string DlgFind_ReplaceAll {
            get {
                return ResourceManager.GetString("DlgFind_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string DlgFind_ReplaceWith {
            get {
                return ResourceManager.GetString("DlgFind_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search up.
        /// </summary>
        public static string DlgFind_SearchUp {
            get {
                return ResourceManager.GetString("DlgFind_SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find:.
        /// </summary>
        public static string DlgFind_TextToFind {
            get {
                return ResourceManager.GetString("DlgFind_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string DlgFind_Wildcards {
            get {
                return ResourceManager.GetString("DlgFind_Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compile.
        /// </summary>
        public static string MenuCompile_Comple {
            get {
                return ResourceManager.GetString("MenuCompile_Comple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate C++ test code.
        /// </summary>
        public static string MenuCompile_GenCpp {
            get {
                return ResourceManager.GetString("MenuCompile_GenCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using unicode name in C++.
        /// </summary>
        public static string MenuCompile_SupportUnicode {
            get {
                return ResourceManager.GetString("MenuCompile_SupportUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuEdit_Copy {
            get {
                return ResourceManager.GetString("MenuEdit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MenuEdit_Cut {
            get {
                return ResourceManager.GetString("MenuEdit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuEdit_Delete {
            get {
                return ResourceManager.GetString("MenuEdit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit_Edit {
            get {
                return ResourceManager.GetString("MenuEdit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimming.
        /// </summary>
        public static string MenuEdit_Indentation {
            get {
                return ResourceManager.GetString("MenuEdit_Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MenuEdit_Paste {
            get {
                return ResourceManager.GetString("MenuEdit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuEdit_Redo {
            get {
                return ResourceManager.GetString("MenuEdit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select all.
        /// </summary>
        public static string MenuEdit_SelectAll {
            get {
                return ResourceManager.GetString("MenuEdit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuEdit_Undo {
            get {
                return ResourceManager.GetString("MenuEdit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile_File {
            get {
                return ResourceManager.GetString("MenuFile_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuFile_New {
            get {
                return ResourceManager.GetString("MenuFile_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuFile_Open {
            get {
                return ResourceManager.GetString("MenuFile_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string MenuFile_OpenFolder {
            get {
                return ResourceManager.GetString("MenuFile_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new _Window .
        /// </summary>
        public static string MenuFile_OpenNewWindow {
            get {
                return ResourceManager.GetString("MenuFile_OpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MenuFile_Print {
            get {
                return ResourceManager.GetString("MenuFile_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string MenuFile_PrintPreview {
            get {
                return ResourceManager.GetString("MenuFile_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string MenuFile_RecentFiles {
            get {
                return ResourceManager.GetString("MenuFile_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuFile_Save {
            get {
                return ResourceManager.GetString("MenuFile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string MenuFile_SaveAll {
            get {
                return ResourceManager.GetString("MenuFile_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save_As.
        /// </summary>
        public static string MenuFile_SaveAs {
            get {
                return ResourceManager.GetString("MenuFile_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; Replace.
        /// </summary>
        public static string MenuFind_FindReplace {
            get {
                return ResourceManager.GetString("MenuFind_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MenuFind_Search {
            get {
                return ResourceManager.GetString("MenuFind_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gherkin Editor.
        /// </summary>
        public static string MenuHelp_About {
            get {
                return ResourceManager.GetString("MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin keywords.
        /// </summary>
        public static string MenuHelp_GherkinKeywords {
            get {
                return ResourceManager.GetString("MenuHelp_GherkinKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp_Help {
            get {
                return ResourceManager.GetString("MenuHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate GUID for scenarios.
        /// </summary>
        public static string MenuSetting_AutoGenGUID {
            get {
                return ResourceManager.GetString("MenuSetting_AutoGenGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string MenuSetting_ChangeLanguage {
            get {
                return ResourceManager.GetString("MenuSetting_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerAvailableColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerAvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerRecentColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerRecentColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerStandardColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerStandardColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants color.
        /// </summary>
        public static string MenuSetting_ConstantsColor {
            get {
                return ResourceManager.GetString("MenuSetting_ConstantsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding scenarios by default.
        /// </summary>
        public static string MenuSetting_DefaultScenarioFolding {
            get {
                return ResourceManager.GetString("MenuSetting_DefaultScenarioFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding tables by default.
        /// </summary>
        public static string MenuSetting_DefaultTableFolding {
            get {
                return ResourceManager.GetString("MenuSetting_DefaultTableFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc string color.
        /// </summary>
        public static string MenuSetting_DocStringColor {
            get {
                return ResourceManager.GetString("MenuSetting_DocStringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding color.
        /// </summary>
        public static string MenuSetting_FoldTextColor {
            get {
                return ResourceManager.GetString("MenuSetting_FoldTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin folding.
        /// </summary>
        public static string MenuSetting_GherkinFolding {
            get {
                return ResourceManager.GetString("MenuSetting_GherkinFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting keywords highlighting.
        /// </summary>
        public static string MenuSetting_GherkinHighlighting {
            get {
                return ResourceManager.GetString("MenuSetting_GherkinHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight current line.
        /// </summary>
        public static string MenuSetting_HighlightCurrentLine {
            get {
                return ResourceManager.GetString("MenuSetting_HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword color.
        /// </summary>
        public static string MenuSetting_KeywordColor {
            get {
                return ResourceManager.GetString("MenuSetting_KeywordColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock color.
        /// </summary>
        public static string MenuSetting_MockColor {
            get {
                return ResourceManager.GetString("MenuSetting_MockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all highlighting colors.
        /// </summary>
        public static string MenuSetting_ResetHighlightingColor {
            get {
                return ResourceManager.GetString("MenuSetting_ResetHighlightingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string MenuSetting_Setting {
            get {
                return ResourceManager.GetString("MenuSetting_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current line border.
        /// </summary>
        public static string MenuSetting_ShowCurrentLineBorder {
            get {
                return ResourceManager.GetString("MenuSetting_ShowCurrentLineBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index by default.
        /// </summary>
        public static string MenuSetting_ShowScenarioIndexByDefault {
            get {
                return ResourceManager.GetString("MenuSetting_ShowScenarioIndexByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor by default.
        /// </summary>
        public static string MenuSetting_SplitEditorByDefault {
            get {
                return ResourceManager.GetString("MenuSetting_SplitEditorByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step word color.
        /// </summary>
        public static string MenuSetting_StepWordColor {
            get {
                return ResourceManager.GetString("MenuSetting_StepWordColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table color.
        /// </summary>
        public static string MenuSetting_TableColor {
            get {
                return ResourceManager.GetString("MenuSetting_TableColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag color.
        /// </summary>
        public static string MenuSetting_TagColor {
            get {
                return ResourceManager.GetString("MenuSetting_TagColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all foldings.
        /// </summary>
        public static string MenuView_FoldOpenAll {
            get {
                return ResourceManager.GetString("MenuView_FoldOpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding scenario.
        /// </summary>
        public static string MenuView_FoldScenario {
            get {
                return ResourceManager.GetString("MenuView_FoldScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding table sections.
        /// </summary>
        public static string MenuView_FoldTables {
            get {
                return ResourceManager.GetString("MenuView_FoldTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show code generation message window.
        /// </summary>
        public static string MenuView_GenCodeMessageWindow {
            get {
                return ResourceManager.GetString("MenuView_GenCodeMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index.
        /// </summary>
        public static string MenuView_ShowScenarioIndex {
            get {
                return ResourceManager.GetString("MenuView_ShowScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor.
        /// </summary>
        public static string MenuView_SplitEditor {
            get {
                return ResourceManager.GetString("MenuView_SplitEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView_View {
            get {
                return ResourceManager.GetString("MenuView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string Message_AboutGherkinAdditionalInfo {
            get {
                return ResourceManager.GetString("Message_AboutGherkinAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GherkinEditor is a text editor for Gherkin feature.
        ///It can generate C++ test code based on GoogleTest..
        /// </summary>
        public static string Message_AboutGherkinDescription {
            get {
                return ResourceManager.GetString("Message_AboutGherkinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin Editor.
        /// </summary>
        public static string Message_AboutGherkinTitle {
            get {
                return ResourceManager.GetString("Message_AboutGherkinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Message_CodeCompletionBackground {
            get {
                return ResourceManager.GetString("Message_CodeCompletionBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Message_CodeCompletionExample {
            get {
                return ResourceManager.GetString("Message_CodeCompletionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Message_CodeCompletionFeature {
            get {
                return ResourceManager.GetString("Message_CodeCompletionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language tag. Any language different from English should be explicitly marked with a #language: ... comment at the beginning of the feature..
        /// </summary>
        public static string Message_CodeCompletionLanguage {
            get {
                return ResourceManager.GetString("Message_CodeCompletionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string Message_CodeCompletionScenario {
            get {
                return ResourceManager.GetString("Message_CodeCompletionScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario outline.
        /// </summary>
        public static string Message_CodeCompletionScenarioOutline {
            get {
                return ResourceManager.GetString("Message_CodeCompletionScenarioOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Message_CodeCompletionStepKeyword {
            get {
                return ResourceManager.GetString("Message_CodeCompletionStepKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to make new language effective.
        /// </summary>
        public static string Message_ConfirmRestartApp {
            get {
                return ResourceManager.GetString("Message_ConfirmRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string Message_ConfirmRestartAppTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmRestartAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you save modified file({0})?.
        /// </summary>
        public static string Message_ConfirmSave {
            get {
                return ResourceManager.GetString("Message_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm save.
        /// </summary>
        public static string Message_ConfirmSaveTile {
            get {
                return ResourceManager.GetString("Message_ConfirmSaveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ test codes are generated..
        /// </summary>
        public static string Message_CppTestCodeGeneration {
            get {
                return ResourceManager.GetString("Message_CppTestCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is following error when generating C++ test code..
        /// </summary>
        public static string Message_HasErrorInCodeGeneration {
            get {
                return ResourceManager.GetString("Message_HasErrorInCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty format completed..
        /// </summary>
        public static string Message_PrettyFormatCompleted {
            get {
                return ResourceManager.GetString("Message_PrettyFormatCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Replace All occurences of &quot;{0}&quot; with &quot;{1}&quot;?.
        /// </summary>
        public static string Message_ReplaceAllConfirm {
            get {
                return ResourceManager.GetString("Message_ReplaceAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items are replaced..
        /// </summary>
        public static string Message_ReplaceAllResult {
            get {
                return ResourceManager.GetString("Message_ReplaceAllResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string Message_ReplaceAllTitle {
            get {
                return ResourceManager.GetString("Message_ReplaceAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate C++ test code after saving current file..
        /// </summary>
        public static string Message_SaveFileBeforeGenCode {
            get {
                return ResourceManager.GetString("Message_SaveFileBeforeGenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code generation error.
        /// </summary>
        public static string Message_SaveFileBeforeGenCodeTitle {
            get {
                return ResourceManager.GetString("Message_SaveFileBeforeGenCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ー Index ー.
        /// </summary>
        public static string Message_ScenarioIndex {
            get {
                return ResourceManager.GetString("Message_ScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled).
        /// </summary>
        public static string Message_UnknownFileName {
            get {
                return ResourceManager.GetString("Message_UnknownFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PrintButton_Cancel {
            get {
                return ResourceManager.GetString("PrintButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default color.
        /// </summary>
        public static string Tooltip_DefaultHighlighingColor {
            get {
                return ResourceManager.GetString("Tooltip_DefaultHighlighingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Tooltip_FontFamilty {
            get {
                return ResourceManager.GetString("Tooltip_FontFamilty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Tooltip_FontSize {
            get {
                return ResourceManager.GetString("Tooltip_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string Tooltip_NewFile {
            get {
                return ResourceManager.GetString("Tooltip_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string Tooltip_OpenFile {
            get {
                return ResourceManager.GetString("Tooltip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string Tooltip_SaveAllFiles {
            get {
                return ResourceManager.GetString("Tooltip_SaveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string Tooltip_SaveFile {
            get {
                return ResourceManager.GetString("Tooltip_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index.
        /// </summary>
        public static string Tooltip_ShowScenarioIndex {
            get {
                return ResourceManager.GetString("Tooltip_ShowScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor.
        /// </summary>
        public static string Tooltip_SplitEditor {
            get {
                return ResourceManager.GetString("Tooltip_SplitEditor", resourceCulture);
            }
        }
    }
}
