//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gherkin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gherkin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string DlgFind_Find {
            get {
                return ResourceManager.GetString("DlgFind_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next(F3).
        /// </summary>
        public static string DlgFind_FindNextToolTip {
            get {
                return ResourceManager.GetString("DlgFind_FindNextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next up(Shift+F3).
        /// </summary>
        public static string DlgFind_FindNextUpToolTip {
            get {
                return ResourceManager.GetString("DlgFind_FindNextUpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string DlgFind_MachCase {
            get {
                return ResourceManager.GetString("DlgFind_MachCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        public static string DlgFind_MachWholdWord {
            get {
                return ResourceManager.GetString("DlgFind_MachWholdWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found!.
        /// </summary>
        public static string DlgFind_NoMatchesFoundText {
            get {
                return ResourceManager.GetString("DlgFind_NoMatchesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more text found. Do you find from start again?.
        /// </summary>
        public static string DlgFind_NoMoreTextFound {
            get {
                return ResourceManager.GetString("DlgFind_NoMoreTextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string DlgFind_RegularExpression {
            get {
                return ResourceManager.GetString("DlgFind_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace(ALT+R).
        /// </summary>
        public static string DlgFind_Replace {
            get {
                return ResourceManager.GetString("DlgFind_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All(ALT+A).
        /// </summary>
        public static string DlgFind_ReplaceAll {
            get {
                return ResourceManager.GetString("DlgFind_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement term.
        /// </summary>
        public static string DlgFind_ReplacementTermText {
            get {
                return ResourceManager.GetString("DlgFind_ReplacementTermText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string DlgFind_ReplaceWith {
            get {
                return ResourceManager.GetString("DlgFind_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        public static string DlgFind_SearchTermText {
            get {
                return ResourceManager.GetString("DlgFind_SearchTermText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search up.
        /// </summary>
        public static string DlgFind_SearchUp {
            get {
                return ResourceManager.GetString("DlgFind_SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find:.
        /// </summary>
        public static string DlgFind_TextToFind {
            get {
                return ResourceManager.GetString("DlgFind_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to switch between find and replace modes.
        /// </summary>
        public static string DlgFind_ToggleFindReplace {
            get {
                return ResourceManager.GetString("DlgFind_ToggleFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string DlgFind_Wildcards {
            get {
                return ResourceManager.GetString("DlgFind_Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string DlgGrepLabel_FileExtensions {
            get {
                return ResourceManager.GetString("DlgGrepLabel_FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grep Options.
        /// </summary>
        public static string DlgGrepLabel_SearchCondition {
            get {
                return ResourceManager.GetString("DlgGrepLabel_SearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string DlgGrepLabel_SearchFolder {
            get {
                return ResourceManager.GetString("DlgGrepLabel_SearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to find.
        /// </summary>
        public static string DlgGrepLabel_TextToFind {
            get {
                return ResourceManager.GetString("DlgGrepLabel_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample extensions(*.feature; *.cs).
        /// </summary>
        public static string DlgGrepTooltip_FileExtensions {
            get {
                return ResourceManager.GetString("DlgGrepTooltip_FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search folder.
        /// </summary>
        public static string DlgGrepTooltip_GrepSearchFolder {
            get {
                return ResourceManager.GetString("DlgGrepTooltip_GrepSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DlgGrepTooltip_GrepStart {
            get {
                return ResourceManager.GetString("DlgGrepTooltip_GrepStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compile.
        /// </summary>
        public static string MenuCompile_Comple {
            get {
                return ResourceManager.GetString("MenuCompile_Comple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate C++ test code.
        /// </summary>
        public static string MenuCompile_GenCpp {
            get {
                return ResourceManager.GetString("MenuCompile_GenCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using unicode name in C++.
        /// </summary>
        public static string MenuCompile_SupportUnicode {
            get {
                return ResourceManager.GetString("MenuCompile_SupportUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file to.
        /// </summary>
        public static string MenuEdit_ContextCopyFileTo {
            get {
                return ResourceManager.GetString("MenuEdit_ContextCopyFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show IntelliSense.
        /// </summary>
        public static string MenuEdit_ContextShowCodeCompletion {
            get {
                return ResourceManager.GetString("MenuEdit_ContextShowCodeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tab.
        /// </summary>
        public static string MenuEdit_ContextTabBackward {
            get {
                return ResourceManager.GetString("MenuEdit_ContextTabBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuEdit_Copy {
            get {
                return ResourceManager.GetString("MenuEdit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MenuEdit_Cut {
            get {
                return ResourceManager.GetString("MenuEdit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuEdit_Delete {
            get {
                return ResourceManager.GetString("MenuEdit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit_Edit {
            get {
                return ResourceManager.GetString("MenuEdit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimming.
        /// </summary>
        public static string MenuEdit_Indentation {
            get {
                return ResourceManager.GetString("MenuEdit_Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MenuEdit_Paste {
            get {
                return ResourceManager.GetString("MenuEdit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuEdit_Redo {
            get {
                return ResourceManager.GetString("MenuEdit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select all.
        /// </summary>
        public static string MenuEdit_SelectAll {
            get {
                return ResourceManager.GetString("MenuEdit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuEdit_Undo {
            get {
                return ResourceManager.GetString("MenuEdit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile_File {
            get {
                return ResourceManager.GetString("MenuFile_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuFile_New {
            get {
                return ResourceManager.GetString("MenuFile_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuFile_Open {
            get {
                return ResourceManager.GetString("MenuFile_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string MenuFile_OpenFolder {
            get {
                return ResourceManager.GetString("MenuFile_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new _Window .
        /// </summary>
        public static string MenuFile_OpenNewWindow {
            get {
                return ResourceManager.GetString("MenuFile_OpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MenuFile_Print {
            get {
                return ResourceManager.GetString("MenuFile_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string MenuFile_PrintPreview {
            get {
                return ResourceManager.GetString("MenuFile_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string MenuFile_RecentFiles {
            get {
                return ResourceManager.GetString("MenuFile_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuFile_Save {
            get {
                return ResourceManager.GetString("MenuFile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string MenuFile_SaveAll {
            get {
                return ResourceManager.GetString("MenuFile_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save_As.
        /// </summary>
        public static string MenuFile_SaveAs {
            get {
                return ResourceManager.GetString("MenuFile_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string MenuFind_FindNextDown {
            get {
                return ResourceManager.GetString("MenuFind_FindNextDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next up.
        /// </summary>
        public static string MenuFind_FindNextUp {
            get {
                return ResourceManager.GetString("MenuFind_FindNextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; Replace.
        /// </summary>
        public static string MenuFind_FindReplace {
            get {
                return ResourceManager.GetString("MenuFind_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grep in files.
        /// </summary>
        public static string MenuFind_Grep {
            get {
                return ResourceManager.GetString("MenuFind_Grep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MenuFind_Search {
            get {
                return ResourceManager.GetString("MenuFind_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gherkin Editor.
        /// </summary>
        public static string MenuHelp_About {
            get {
                return ResourceManager.GetString("MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Help.
        /// </summary>
        public static string MenuHelp_GherkinHelp {
            get {
                return ResourceManager.GetString("MenuHelp_GherkinHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin keywords.
        /// </summary>
        public static string MenuHelp_GherkinKeywords {
            get {
                return ResourceManager.GetString("MenuHelp_GherkinKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp_Help {
            get {
                return ResourceManager.GetString("MenuHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaTeX Math Symbols.
        /// </summary>
        public static string MenuHelp_LaTeXSymbols {
            get {
                return ResourceManager.GetString("MenuHelp_LaTeXSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate GUID for scenarios.
        /// </summary>
        public static string MenuSetting_AutoGenGUID {
            get {
                return ResourceManager.GetString("MenuSetting_AutoGenGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string MenuSetting_ChangeLanguage {
            get {
                return ResourceManager.GetString("MenuSetting_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerAvailableColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerAvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerRecentColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerRecentColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colors.
        /// </summary>
        public static string MenuSetting_ColorPickerStandardColorsHeader {
            get {
                return ResourceManager.GetString("MenuSetting_ColorPickerStandardColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column ruler position.
        /// </summary>
        public static string MenuSetting_ColumnRulerPosition {
            get {
                return ResourceManager.GetString("MenuSetting_ColumnRulerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants color.
        /// </summary>
        public static string MenuSetting_ConstantsColor {
            get {
                return ResourceManager.GetString("MenuSetting_ConstantsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert tabs to spaces.
        /// </summary>
        public static string MenuSetting_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("MenuSetting_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding scenarios by default.
        /// </summary>
        public static string MenuSetting_DefaultScenarioFolding {
            get {
                return ResourceManager.GetString("MenuSetting_DefaultScenarioFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding tables by default.
        /// </summary>
        public static string MenuSetting_DefaultTableFolding {
            get {
                return ResourceManager.GetString("MenuSetting_DefaultTableFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc string color.
        /// </summary>
        public static string MenuSetting_DocStringColor {
            get {
                return ResourceManager.GetString("MenuSetting_DocStringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding color.
        /// </summary>
        public static string MenuSetting_FoldTextColor {
            get {
                return ResourceManager.GetString("MenuSetting_FoldTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin folding.
        /// </summary>
        public static string MenuSetting_GherkinFolding {
            get {
                return ResourceManager.GetString("MenuSetting_GherkinFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin keywords highlighting.
        /// </summary>
        public static string MenuSetting_GherkinHighlighting {
            get {
                return ResourceManager.GetString("MenuSetting_GherkinHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight current line.
        /// </summary>
        public static string MenuSetting_HighlightCurrentLine {
            get {
                return ResourceManager.GetString("MenuSetting_HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword color.
        /// </summary>
        public static string MenuSetting_KeywordColor {
            get {
                return ResourceManager.GetString("MenuSetting_KeywordColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock color.
        /// </summary>
        public static string MenuSetting_MockColor {
            get {
                return ResourceManager.GetString("MenuSetting_MockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open web browser in Ctrl + Click.
        /// </summary>
        public static string MenuSetting_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("MenuSetting_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset highlighting colors.
        /// </summary>
        public static string MenuSetting_ResetHighlightingColor {
            get {
                return ResourceManager.GetString("MenuSetting_ResetHighlightingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string MenuSetting_Setting {
            get {
                return ResourceManager.GetString("MenuSetting_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail settings.
        /// </summary>
        public static string MenuSetting_SettingMenuHeader {
            get {
                return ResourceManager.GetString("MenuSetting_SettingMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show column ruler.
        /// </summary>
        public static string MenuSetting_ShowColumnRuler {
            get {
                return ResourceManager.GetString("MenuSetting_ShowColumnRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current line border.
        /// </summary>
        public static string MenuSetting_ShowCurrentLineBorder {
            get {
                return ResourceManager.GetString("MenuSetting_ShowCurrentLineBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show end of line.
        /// </summary>
        public static string MenuSetting_ShowEndOfLine {
            get {
                return ResourceManager.GetString("MenuSetting_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index by default.
        /// </summary>
        public static string MenuSetting_ShowScenarioIndexByDefault {
            get {
                return ResourceManager.GetString("MenuSetting_ShowScenarioIndexByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show spaces.
        /// </summary>
        public static string MenuSetting_ShowSpaces {
            get {
                return ResourceManager.GetString("MenuSetting_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs.
        /// </summary>
        public static string MenuSetting_ShowTabs {
            get {
                return ResourceManager.GetString("MenuSetting_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special symbols.
        /// </summary>
        public static string MenuSetting_SpecialSymbols {
            get {
                return ResourceManager.GetString("MenuSetting_SpecialSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split horizontal editor by default.
        /// </summary>
        public static string MenuSetting_SplitHorizontalEditorByDefault {
            get {
                return ResourceManager.GetString("MenuSetting_SplitHorizontalEditorByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split vertical editor by default.
        /// </summary>
        public static string MenuSetting_SplitVerticalEditorByDefault {
            get {
                return ResourceManager.GetString("MenuSetting_SplitVerticalEditorByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step word color.
        /// </summary>
        public static string MenuSetting_StepWordColor {
            get {
                return ResourceManager.GetString("MenuSetting_StepWordColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table color.
        /// </summary>
        public static string MenuSetting_TableColor {
            get {
                return ResourceManager.GetString("MenuSetting_TableColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag color.
        /// </summary>
        public static string MenuSetting_TagColor {
            get {
                return ResourceManager.GetString("MenuSetting_TagColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search highlighting.
        /// </summary>
        public static string MenuTab_ClearSearchHighlighting {
            get {
                return ResourceManager.GetString("MenuTab_ClearSearchHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuTab_Close {
            get {
                return ResourceManager.GetString("MenuTab_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string MenuTab_CloseAllButThis {
            get {
                return ResourceManager.GetString("MenuTab_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Documents.
        /// </summary>
        public static string MenuTab_CloseAllDocuments {
            get {
                return ResourceManager.GetString("MenuTab_CloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new editor.
        /// </summary>
        public static string MenuTab_OpenInNewEditor {
            get {
                return ResourceManager.GetString("MenuTab_OpenInNewEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string MenuTab_Rename {
            get {
                return ResourceManager.GetString("MenuTab_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview document.
        /// </summary>
        public static string MenuTool_PreviewDocument {
            get {
                return ResourceManager.GetString("MenuTool_PreviewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string MenuTool_SaveAsPDF {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF(Print version).
        /// </summary>
        public static string MenuTool_SaveAsPDFBySharpPDF {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsPDFBySharpPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF(by Word).
        /// </summary>
        public static string MenuTool_SaveAsPDFByWord {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsPDFByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as RTF.
        /// </summary>
        public static string MenuTool_SaveAsRTF {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as word file(by Word).
        /// </summary>
        public static string MenuTool_SaveAsWord {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as XPS.
        /// </summary>
        public static string MenuTool_SaveAsXPS {
            get {
                return ResourceManager.GetString("MenuTool_SaveAsXPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuTool_Tools {
            get {
                return ResourceManager.GetString("MenuTool_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all foldings.
        /// </summary>
        public static string MenuView_FoldOpenAll {
            get {
                return ResourceManager.GetString("MenuView_FoldOpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding scenario.
        /// </summary>
        public static string MenuView_FoldScenario {
            get {
                return ResourceManager.GetString("MenuView_FoldScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folding table sections.
        /// </summary>
        public static string MenuView_FoldTables {
            get {
                return ResourceManager.GetString("MenuView_FoldTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plot marker.
        /// </summary>
        public static string MenuView_ShowCurvePlotMarker {
            get {
                return ResourceManager.GetString("MenuView_ShowCurvePlotMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index.
        /// </summary>
        public static string MenuView_ShowScenarioIndex {
            get {
                return ResourceManager.GetString("MenuView_ShowScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor horizontal.
        /// </summary>
        public static string MenuView_SplitHorizontalEditor {
            get {
                return ResourceManager.GetString("MenuView_SplitHorizontalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor vertical.
        /// </summary>
        public static string MenuView_SplitVerticalEditor {
            get {
                return ResourceManager.GetString("MenuView_SplitVerticalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize cursor positions.
        /// </summary>
        public static string MenuView_SynchronizeCursorPositions {
            get {
                return ResourceManager.GetString("MenuView_SynchronizeCursorPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open document by native application .
        /// </summary>
        public static string MenuView_UseNativeDocumentApplication {
            get {
                return ResourceManager.GetString("MenuView_UseNativeDocumentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView_View {
            get {
                return ResourceManager.GetString("MenuView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide work area window.
        /// </summary>
        public static string MenuView_WorkAreaEditor {
            get {
                return ResourceManager.GetString("MenuView_WorkAreaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string Message_AboutGherkinAdditionalInfo {
            get {
                return ResourceManager.GetString("Message_AboutGherkinAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GherkinEditor is a text editor for Gherkin feature.
        ///It can generate C++ test code based on GoogleTest..
        /// </summary>
        public static string Message_AboutGherkinDescription {
            get {
                return ResourceManager.GetString("Message_AboutGherkinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gherkin Editor.
        /// </summary>
        public static string Message_AboutGherkinTitle {
            get {
                return ResourceManager.GetString("Message_AboutGherkinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Message_CodeCompletionBackground {
            get {
                return ResourceManager.GetString("Message_CodeCompletionBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Message_CodeCompletionExample {
            get {
                return ResourceManager.GetString("Message_CodeCompletionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Message_CodeCompletionFeature {
            get {
                return ResourceManager.GetString("Message_CodeCompletionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language tag. Any language different from English should be explicitly marked with a #language: ... comment at the beginning of the feature..
        /// </summary>
        public static string Message_CodeCompletionLanguage {
            get {
                return ResourceManager.GetString("Message_CodeCompletionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string Message_CodeCompletionScenario {
            get {
                return ResourceManager.GetString("Message_CodeCompletionScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario outline.
        /// </summary>
        public static string Message_CodeCompletionScenarioOutline {
            get {
                return ResourceManager.GetString("Message_CodeCompletionScenarioOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Message_CodeCompletionStepKeyword {
            get {
                return ResourceManager.GetString("Message_CodeCompletionStepKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you reload current file in selected encoding?
        ///Any change of the file would be discarded..
        /// </summary>
        public static string Message_ConfirmReloadFileMessage {
            get {
                return ResourceManager.GetString("Message_ConfirmReloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload File.
        /// </summary>
        public static string Message_ConfirmReloadFileTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmReloadFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to make new language effective.
        /// </summary>
        public static string Message_ConfirmRestartApp {
            get {
                return ResourceManager.GetString("Message_ConfirmRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string Message_ConfirmRestartAppTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmRestartAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you save modified file({0})?.
        /// </summary>
        public static string Message_ConfirmSave {
            get {
                return ResourceManager.GetString("Message_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm save.
        /// </summary>
        public static string Message_ConfirmSaveTile {
            get {
                return ResourceManager.GetString("Message_ConfirmSaveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is copied to  - &quot;{0}&quot;.
        /// </summary>
        public static string Message_CopyFileToResult {
            get {
                return ResourceManager.GetString("Message_CopyFileToResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ test codes are generated..
        /// </summary>
        public static string Message_CppTestCodeGeneration {
            get {
                return ResourceManager.GetString("Message_CppTestCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file to.
        /// </summary>
        public static string Message_DlgCopyFileToTitle {
            get {
                return ResourceManager.GetString("Message_DlgCopyFileToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is following error when generating C++ test code..
        /// </summary>
        public static string Message_HasErrorInCodeGeneration {
            get {
                return ResourceManager.GetString("Message_HasErrorInCodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty format completed..
        /// </summary>
        public static string Message_PrettyFormatCompleted {
            get {
                return ResourceManager.GetString("Message_PrettyFormatCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex note.
        /// </summary>
        public static string Message_RegexNoteTitle {
            get {
                return ResourceManager.GetString("Message_RegexNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename failed.
        /// </summary>
        public static string Message_RenameFailedTitle {
            get {
                return ResourceManager.GetString("Message_RenameFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Replace All occurences of &quot;{0}&quot; with &quot;{1}&quot;?.
        /// </summary>
        public static string Message_ReplaceAllConfirm {
            get {
                return ResourceManager.GetString("Message_ReplaceAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items are replaced..
        /// </summary>
        public static string Message_ReplaceAllResult {
            get {
                return ResourceManager.GetString("Message_ReplaceAllResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string Message_ReplaceAllTitle {
            get {
                return ResourceManager.GetString("Message_ReplaceAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate C++ test code after saving current file..
        /// </summary>
        public static string Message_SaveFileBeforeGenCode {
            get {
                return ResourceManager.GetString("Message_SaveFileBeforeGenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code generation error.
        /// </summary>
        public static string Message_SaveFileBeforeGenCodeTitle {
            get {
                return ResourceManager.GetString("Message_SaveFileBeforeGenCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ー Index ー.
        /// </summary>
        public static string Message_ScenarioIndex {
            get {
                return ResourceManager.GetString("Message_ScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled).
        /// </summary>
        public static string Message_UnknownFileName {
            get {
                return ResourceManager.GetString("Message_UnknownFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview_Title {
            get {
                return ResourceManager.GetString("Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PrintButton_Cancel {
            get {
                return ResourceManager.GetString("PrintButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Status_CodePageListTitle {
            get {
                return ResourceManager.GetString("Status_CodePageListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file in selected encoding.
        /// </summary>
        public static string Status_ReloadFileWithCodePage {
            get {
                return ResourceManager.GetString("Status_ReloadFileWithCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file in selected encoding.
        /// </summary>
        public static string Status_SaveAsWithCodePage {
            get {
                return ResourceManager.GetString("Status_SaveAsWithCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear status message.
        /// </summary>
        public static string Tooltip_ClearStatus {
            get {
                return ResourceManager.GetString("Tooltip_ClearStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Copy file by &quot;Copy file to&quot; context menu.
        ///2. Use Ctr key to open a file..
        /// </summary>
        public static string Tooltip_CPPCodeGenResultUage {
            get {
                return ResourceManager.GetString("Tooltip_CPPCodeGenResultUage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default color.
        /// </summary>
        public static string Tooltip_DefaultHighlighingColor {
            get {
                return ResourceManager.GetString("Tooltip_DefaultHighlighingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font1.
        /// </summary>
        public static string Tooltip_FontFamily4NonGherkinText {
            get {
                return ResourceManager.GetString("Tooltip_FontFamily4NonGherkinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default font.
        /// </summary>
        public static string Tooltip_FontFamilyDefault {
            get {
                return ResourceManager.GetString("Tooltip_FontFamilyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font for Non Gherkin.
        /// </summary>
        public static string Tooltip_FontFamilyDefault4NonGherkin {
            get {
                return ResourceManager.GetString("Tooltip_FontFamilyDefault4NonGherkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Tooltip_FontFamilyText {
            get {
                return ResourceManager.GetString("Tooltip_FontFamilyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font for Gherkin document.
        /// </summary>
        public static string Tooltip_FontForGherkin {
            get {
                return ResourceManager.GetString("Tooltip_FontForGherkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font for Non Gherkin document.
        /// </summary>
        public static string Tooltip_FontForNonGherkin {
            get {
                return ResourceManager.GetString("Tooltip_FontForNonGherkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Tooltip_FontSize {
            get {
                return ResourceManager.GetString("Tooltip_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size for Gherkin document.
        /// </summary>
        public static string Tooltip_FontSizeForGherkin {
            get {
                return ResourceManager.GetString("Tooltip_FontSizeForGherkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size for Non Gherkin document.
        /// </summary>
        public static string Tooltip_FontSizeForNonGherkin {
            get {
                return ResourceManager.GetString("Tooltip_FontSizeForNonGherkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide sub editor.
        /// </summary>
        public static string Tooltip_HideSubEditor {
            get {
                return ResourceManager.GetString("Tooltip_HideSubEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide viewer editor.
        /// </summary>
        public static string Tooltip_HideViewerEditor {
            get {
                return ResourceManager.GetString("Tooltip_HideViewerEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide work area window.
        /// </summary>
        public static string Tooltip_HideWorkAreaEditor {
            get {
                return ResourceManager.GetString("Tooltip_HideWorkAreaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string Tooltip_NewFile {
            get {
                return ResourceManager.GetString("Tooltip_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened documents.
        /// </summary>
        public static string Tooltip_OpenedDocuments {
            get {
                return ResourceManager.GetString("Tooltip_OpenedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string Tooltip_OpenFile {
            get {
                return ResourceManager.GetString("Tooltip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ctrl key to open URL by Web browser.
        /// </summary>
        public static string Tooltip_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("Tooltip_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string Tooltip_SaveAllFiles {
            get {
                return ResourceManager.GetString("Tooltip_SaveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string Tooltip_SaveFile {
            get {
                return ResourceManager.GetString("Tooltip_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to left.
        /// </summary>
        public static string Tooltip_ScrollLeft {
            get {
                return ResourceManager.GetString("Tooltip_ScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to right.
        /// </summary>
        public static string Tooltip_ScrollRight {
            get {
                return ResourceManager.GetString("Tooltip_ScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gherkin table plot marker.
        /// </summary>
        public static string Tooltip_ShowCurvePlotMarker {
            get {
                return ResourceManager.GetString("Tooltip_ShowCurvePlotMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scenario index.
        /// </summary>
        public static string Tooltip_ShowScenarioIndex {
            get {
                return ResourceManager.GetString("Tooltip_ShowScenarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sub editor.
        /// </summary>
        public static string Tooltip_ShowSubEditor {
            get {
                return ResourceManager.GetString("Tooltip_ShowSubEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show viewer editor.
        /// </summary>
        public static string Tooltip_ShowViewerEditor {
            get {
                return ResourceManager.GetString("Tooltip_ShowViewerEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show work area window.
        /// </summary>
        public static string Tooltip_ShowWorkAreaEditor {
            get {
                return ResourceManager.GetString("Tooltip_ShowWorkAreaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor horizontal.
        /// </summary>
        public static string Tooltip_SplitHorizontalEditor {
            get {
                return ResourceManager.GetString("Tooltip_SplitHorizontalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split editor vertical.
        /// </summary>
        public static string Tooltip_SplitVerticalEditor {
            get {
                return ResourceManager.GetString("Tooltip_SplitVerticalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize cursor positions of main and sub editors.
        /// </summary>
        public static string Tooltip_SynchronizeCursorPositions {
            get {
                return ResourceManager.GetString("Tooltip_SynchronizeCursorPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After saving as PDF, XPS, RTF or Word, open the document by Windows native application.
        /// </summary>
        public static string Tooltip_UseNativeDocumentApplication {
            get {
                return ResourceManager.GetString("Tooltip_UseNativeDocumentApplication", resourceCulture);
            }
        }
    }
}
